@CalendarWebsite.Server_HostAddress = https://localhost:7179

GET {{CalendarWebsite.Server_HostAddress}}/api/DataOnly_APIaCheckIn/GetAllUsersName
# Accept: application/json

###

GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetAllUsersName

###
